# Hyprland config — modular layout
# Docs: https://wiki.hypr.land/Configuring/

################
### MACHINE  ###
################
# Selecciona la config según la máquina.
# Para MSI:    descomentar _msi,    comentar _legion
# Para Legion: descomentar _legion, comentar _msi
source = ~/.config/hypr/conf/monitors_msi.conf
source = ~/.config/hypr/conf/workspaces_msi.conf
#source = ~/.config/hypr/conf/monitors_legion.conf
#source = ~/.config/hypr/conf/workspaces_legion.conf

####################
### CORE MODULES ###
####################
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/rules.conf
