# Hyprland config — modular layout
# Docs: https://wiki.hypr.land/Configuring/

################
### MACHINE  ###
################
# Selecciona la config según la máquina.
# Para MSI:    descomentar _msi,    comentar _legion
# Para Legion: descomentar _legion, comentar _msi
source = ~/.config/hypr/conf.d/monitors_msi.conf
source = ~/.config/hypr/conf.d/workspaces_msi.conf
#source = ~/.config/hypr/conf.d/monitors_legion.conf
#source = ~/.config/hypr/conf.d/workspaces_legion.conf

####################
### CORE MODULES ###
####################
source = ~/.config/hypr/conf.d/env.conf
source = ~/.config/hypr/conf.d/appearance.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/autostart.conf
source = ~/.config/hypr/conf.d/keybinds.conf
source = ~/.config/hypr/conf.d/rules.conf
