################
### MONITORS ###
################

# ------------------------------------------------------------------
# SETUP LEGION (ajusta según hyprctl monitors en el portátil)
#monitor = eDP-1, preferred, 0x0, 1
# ------------------------------------------------------------------


##################
### WORKSPACES ###
##################
# Ajusta según los monitores del LEGION
#workspace = 1, monitor:eDP-1, default:true, persistent:true
#workspace = 2, monitor:eDP-1, persistent:true
#workspace = 3, monitor:eDP-1, persistent:true
#workspace = 4, monitor:eDP-1, persistent:true
#workspace = 5, monitor:eDP-1, persistent:true
