#################
### AUTOSTART ###
#################

# Core services
exec-once = waybar --config ~/.config/waybar/config --style ~/.config/waybar/style.css
exec-once = dunst
exec-once = swayosd-server --top-margin 0.99
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Wallpaper
#exec-once = hyprpaper
#exec-once = ~/.config/hypr/scripts/random-wall-video.sh
exec-once = ~/.config/hypr/scripts/random-wall.sh

# Dock & audio
exec-once = nwg-dock-hyprland -d -i 40 -mb 8 -nolauncher -hd 0 -l overlay
exec-once = easyeffects --window=hide

# Cursor
exec-once = hyprctl setcursor Bibata-Modern-Ice 23
