#############
### INPUT ###
#############

input {
    kb_layout = es
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    numlock_by_default = true
    sensitivity = 0
    force_no_accel = true
    accel_profile = flat

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    accel_profile = flat
    sensitivity = -0.5
}
